services:
  vncp-home-assistant:
    image: ghcr.io/versa-node/vncp-home-assistant:latest
    container_name: vncp-home-assistant
    restart: unless-stopped
    env_file: ./.env
        networks: [versanode]

networks:
  versanode:
    external: true
    name: versanode
