services:
  vncp-home-assistant:
    image: ghcr.io/<your-org>/vncp-home-assistant:latest
    container_name: vncp-home-assistant
    restart: unless-stopped
    env_file: ./.env

    network_mode: host
    privileged: true
    volumes:
      - ./config:/config
    healthcheck:
      test: ["CMD", "bash", "-lc", "[ -f /config/.storage/core.config_entries ] || exit 1"]
      interval: 60s
      timeout: 10s
      retries: 5

    networks: [versanode]

networks:
  versanode:
    external: true
    name: versanode
