name: vncp-home-assistant
description: Home Assistant (home automation)
arch: [linux/arm64]
maintainers:
  - name: Community
    github: versanode-community
upstream:
  image: ghcr.io/home-assistant/home-assistant:stable
ports: []
volumes: []
env: []
healthcheck:
  test: ["CMD", "bash", "-lc", "echo ok"]
  interval: 30s
  timeout: 5s
  retries: 3
