version: 1
metadata:
  id: vncp-postgresql
  name: PostgreSQL
  summary: PostgreSQL 16 database
  website: https://www.postgresql.org/
parameters:
  - key: PG_PORT
    label: Host Port
    type: port
    description: Port exposed on the host for PostgreSQL
    default: 5432
  - key: POSTGRES_USER
    label: Username
    type: string
    description: Database superuser name
    default: postgres
    required: true
  - key: POSTGRES_PASSWORD
    label: Password
    type: password
    description: Database superuser password
    default: postgres
    required: true
    secret: true
  - key: POSTGRES_DB
    label: Database
    type: string
    description: Default database to create
    default: app
  - key: DATA_PATH
    label: Data path (host)
    type: path
    description: Host folder for PostgreSQL data
    default: ./data
mappings:
  env: [ PG_PORT, POSTGRES_USER, POSTGRES_PASSWORD, POSTGRES_DB ]
  files: []
notes:
  - "Map DATA_PATH to ./data in compose."
