services:
  vncp-timescaledb:
    image: ghcr.io/versa-node/vncp-timescaledb:latest
    platform: linux/arm64
    container_name: vncp-timescaledb
    restart: unless-stopped
    env_file: ./.env
        ports:
  - "${PG_PORT:-5432}:5432"
    networks: [versanode]

networks:
  versanode:
    external: true
    name: versanode
