name: vncp-nas-samba
description: Simple Samba NAS container for a single share
arch: [linux/arm64, linux/amd64]
maintainers:
  - name: Community
    github: versanode-community
upstream:
  image: ""
ports:
  - "445:445"
volumes:
  - "./data:/shares/${SAMBA_SHARE_NAME:-share}"
env:
  - "SAMBA_USER=user"
  - "SAMBA_PASS=pass"
  - "SAMBA_SHARE_NAME=share"
healthcheck:
  test: ["CMD", "bash", "-lc", "nc -z localhost 445"]
  interval: 30s
  timeout: 5s
  retries: 5
