name: vncp-esphome
description: 
arch: [linux/arm64]
maintainers:
  - name: Community
    github: versanode-community
upstream:
  image: ghcr.io/esphome/esphome:latest
ports: []
volumes: []
env: []
healthcheck:
  test: ["CMD", "bash", "-lc", "nc -z localhost 6052"]
  interval: 30s
  timeout: 5s
  retries: 5
