services:
  vncp-nodered:
    image: ghcr.io/<your-org>/vncp-nodered:latest
    container_name: vncp-nodered
    restart: unless-stopped
    env_file: ./.env

    ports:
      - "${NODERED_PORT:-1880}:1880"
    volumes:
      - ./data:/data
    healthcheck:
      test: ["CMD", "bash", "-lc", "curl -fsS http://localhost:1880 || exit 1"]
      interval: 30s
      timeout: 5s
      retries: 5

    networks: [versanode]

networks:
  versanode:
    external: true
    name: versanode
