name: vncp-nodered
description: Node-RED flow-based development tool
arch: [linux/arm64]
maintainers:
  - name: Community
    github: versanode-community
upstream:
  image: docker.io/nodered/node-red:latest
ports: []
volumes: []
env: []
healthcheck:
  test: ["CMD", "bash", "-lc", "echo ok"]
  interval: 30s
  timeout: 5s
  retries: 3
