name: mosquitto
description: Eclipse Mosquitto MQTT broker
arch: [linux/arm64, linux/amd64]
maintainers:
  - name: Community
    github: versanode-community
upstream:
  image: eclipse-mosquitto:2
ports:
  - "1883:1883"
  - "9001:9001"
volumes:
  - "./config:/mosquitto/config"
  - "./data:/mosquitto/data"
  - "./log:/mosquitto/log"
env: []
healthcheck:
  test: ["CMD", "mosquitto_ctrl", "status"]
  interval: 30s
  timeout: 5s
  retries: 3
