services:
  vncp-apn:
    image: ghcr.io/versa-node/vncp-apn:latest
    container_name: vncp-apn
    restart: unless-stopped
    env_file: ./.env
        networks: [versanode]

networks:
  versanode:
    external: true
    name: versanode
