name: vncp-apn
description: Cellular APN dialer (PPP)
arch: [linux/arm64]
maintainers:
  - name: Community
    github: versanode-community
upstream:
  image: ""
ports: []
volumes: []
env: []
healthcheck:
  test: ["CMD", "bash", "-lc", "ping -c1 -W2 8.8.8.8 >/dev/null 2>&1 || exit 1"]
  interval: 60s
  timeout: 10s
  retries: 5
