services:
  vncp-influxdb:
    image: ghcr.io/versa-node/vncp-influxdb:latest
    container_name: vncp-influxdb
    restart: unless-stopped
    env_file: ./.env

    ports:
      - "${INFLUXDB_PORT:-8086}:8086"
    volumes:
      - ./data:/var/lib/influxdb2
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=${INFLUXDB_INIT_MODE:-setup}
      - DOCKER_INFLUXDB_INIT_USERNAME=${INFLUXDB_USERNAME:-admin}
      - DOCKER_INFLUXDB_INIT_PASSWORD=${INFLUXDB_PASSWORD:-changeme}
      - DOCKER_INFLUXDB_INIT_ORG=${INFLUXDB_ORG:-versanode}
      - DOCKER_INFLUXDB_INIT_BUCKET=${INFLUXDB_BUCKET:-default}
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=${INFLUXDB_TOKEN:-}
    healthcheck:
      test: ["CMD", "bash", "-lc", "wget -qO- http://localhost:8086/health | grep -q pass"]
      interval: 30s
      timeout: 10s
      retries: 5
    networks: [versanode]

networks:
  versanode:
    external: true
    name: versanode
