services:
  vncp-influxdb:
    image: ghcr.io/versa-node/vncp-influxdb:latest
    platform: linux/arm64
    container_name: vncp-influxdb
    restart: unless-stopped
    env_file: ./.env
        ports:
  - "${INFLUXDB_PORT:-8086}:8086"
    networks: [versanode]

networks:
  versanode:
    external: true
    name: versanode
