services:
  vncp-openhab:
    image: ghcr.io/versa-node/vncp-openhab:latest
    platform: linux/arm64
    container_name: vncp-openhab
    restart: unless-stopped
    networks: [versanode]
  volumes:
      - /var/lib/vncp/props:/vncp/props:rw
      - ./scripts/vncp-openhab-dashprop:/usr/local/bin/vncp-openhab-dashprop:ro
  healthcheck:
      test: ["CMD-SHELL", "/usr/local/bin/vncp-openhab-dashprop || true"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 5s         # makes it run soon after boot