services:
  vncp-openhab:
    image: ghcr.io/versa-node/vncp-openhab:latest
    restart: always

    # Attach to the versanode network (create externally once)
    networks: [versanode]

    # Bind-mount time + standard openHAB data dirs
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - ./openhab_addons:/openhab/addons
      - ./openhab_conf:/openhab/conf
      - ./openhab_userdata:/openhab/userdata

      # VNCP: host-readable dashboards property
      - /var/lib/vncp:/vncp:rw
      # VNCP: publisher script (omit if baked into image)
      - ./scripts/vncp-openhab-dashprop:/usr/local/bin/vncp-openhab-dashprop:ro

    # Map host → container ports (change host ports if needed)
    ports:
      - "${HOST_HTTP_PORT:-8080}:${OPENHAB_HTTP_PORT:-8080}"
      - "${HOST_HTTPS_PORT:-8443}:${OPENHAB_HTTPS_PORT:-8443}"

    environment:
      CRYPTO_POLICY: "unlimited"
      EXTRA_JAVA_OPTS: "-Duser.timezone=Europe/Berlin"
      OPENHAB_HTTP_PORT: "8080"
      OPENHAB_HTTPS_PORT: "8443"

    # Healthcheck also updates dashboard property when healthy
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "for url in https://127.0.0.1:${OPENHAB_HTTPS_PORT:-8443} http://127.0.0.1:${OPENHAB_HTTP_PORT:-8080}; do \
             if curl -skI --connect-timeout 2 --max-time 4 \"$url\" \
               | grep -qE 'HTTP/.* (2..|3..|401|403)'; then \
               /usr/local/bin/vncp-openhab-dashprop || true; exit 0; fi; done; exit 1"
        ]
      interval: 30s
      timeout: 5s
      retries: 10
      start_period: 180s

networks:
  versanode:
    external: true
    name: versanode
