services:
  vncp-pycaret-notebook:
    image: ghcr.io/versa-node/vncp-pycaret-notebook:latest
    platform: linux/arm64
    container_name: vncp-pycaret-notebook
    restart: unless-stopped
    env_file: ./.env
        ports:
  - "${JUPYTER_PORT:-8888}:8888"
    networks: [versanode]

networks:
  versanode:
    external: true
    name: versanode
