name: nodered
description: Low-code flow-based development tool
arch: [linux/arm64, linux/amd64]
maintainers:
  - name: Community
    github: versanode-community
upstream:
  image: nodered/node-red:latest
ports:
  - "1880:1880"
volumes:
  - "./data:/data"
env: []
healthcheck:
  test: ["CMD", "bash", "-lc", "curl -fsS http://localhost:1880 || exit 1"]
  interval: 30s
  timeout: 5s
  retries: 5
