name: vncp-mosquitto
description: Eclipse Mosquitto MQTT broker
arch: [linux/arm64, linux/amd64]
maintainers:
  - name: Community
    github: versanode-community
upstream:
  image: docker.io/eclipse-mosquitto:2
ports: []
volumes: []
env: []
healthcheck:
  test: ["CMD", "bash", "-lc", "echo ok"]
  interval: 30s
  timeout: 5s
  retries: 3
