services:
  vncp-zigbee2mqtt:
    image: ghcr.io/versa-node/vncp-zigbee2mqtt:latest
    platform: linux/arm64
    container_name: vncp-zigbee2mqtt
    restart: unless-stopped
    env_file: ./.env
        ports:
  - "${Z2M_UI_PORT:-8080}:8080"
    networks: [versanode]

networks:
  versanode:
    external: true
    name: versanode
