services:
  vncp-grafana:
    image: ghcr.io/versa-node/vncp-grafana:latest
    container_name: vncp-grafana
    restart: unless-stopped
    env_file: ./.env

    ports:
      - "${GRAFANA_PORT:-3000}:3000"
    volumes:
      - ./data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_USER=${GRAFANA_ADMIN_USER:-admin}
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_ADMIN_PASSWORD:-admin}
    healthcheck:
      test: ["CMD", "bash", "-lc", "nc -z localhost 3000"]
      interval: 30s
      timeout: 5s
      retries: 5
    networks: [versanode]

networks:
  versanode:
    external: true
    name: versanode
