version: 1
metadata:
  id: vncp-grafana
  name: Grafana
  summary: Grafana dashboards for time-series data
  website: https://grafana.com/
parameters:
  - key: GRAFANA_PORT
    label: Grafana port
    type: port
    description: Host port for Grafana UI
    default: 3000
  - key: GRAFANA_ADMIN_USER
    label: Admin username
    type: string
    description: Grafana admin username
    default: admin
  - key: GRAFANA_ADMIN_PASSWORD
    label: Admin password
    type: password
    description: Grafana admin password
    default: admin
    secret: true
mappings:
  env: [ GRAFANA_PORT, GRAFANA_ADMIN_USER, GRAFANA_ADMIN_PASSWORD ]
  files: []
