services:
  vncp-template:
    image: ghcr.io/<your-org>/vncp-template:latest
    container_name: vncp-template
    restart: unless-stopped
    env_file: ./.env

    networks: [versanode]

networks:
  versanode:
    external: true
    name: versanode
