name: vncp-template
description: Replace me with a short one-liner
arch: [linux/arm64, linux/amd64]
maintainers:
  - name: Your Name
    github: yourhandle
upstream:
  image: ""
ports: []
volumes: []
env: []
healthcheck:
  test: ["CMD", "true"]
  interval: 30s
  timeout: 5s
  retries: 1
