version: 1
metadata:
  id: vncp-template
  name: Template
  summary: Starter template package
  website: https://example.com
parameters:
  - key: EXAMPLE_PORT
    label: Example port
    type: port
    description: Example host port to expose
    default: 1234
mappings:
  env: [ EXAMPLE_PORT ]
  files: []
notes:
  - "Copy this folder and adjust."
