name: home-assistant
description: Open source home automation
arch: [linux/arm64, linux/amd64]
maintainers:
  - name: Community
    github: versanode-community
upstream:
  image: ghcr.io/home-assistant/home-assistant:stable
ports: []
volumes:
  - "./config:/config"
env: []
healthcheck:
  test: ["CMD", "bash", "-lc", "[ -f /config/.storage/core.config_entries ] || exit 1"]
  interval: 60s
  timeout: 10s
  retries: 5
